#!/usr/bin/env python3
"""Regenerates IMPLEMENTATION_DETAILS.json from the bundled sample manifests and the model registry.

Run after `scripts/samples/build.py` changes the library. It never runs as part of pnpm build/test.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SAMPLES = os.path.join(ROOT, 'public', 'samples')

index = json.load(open(os.path.join(SAMPLES, 'index.json')))
registry = open(os.path.join(ROOT, 'src', 'audio', 'pianoModels.ts')).read()

sample_sources = []
for entry in index['sets']:
    m = json.load(open(os.path.join(SAMPLES, entry['id'], 'manifest.json')))
    files = [f['file'] for f in m['files']]
    roots = sorted({f['root'] for f in m['files']})
    layers = [f"{l['name']} ({l['lovel']}-{l['hivel']})" for l in m['layers']]
    sample_sources.append({
        'name': f"{m['type']} · {m['model']}",
        'setId': m['id'],
        'kind': 'recorded-samples',
        'source': f"{m['source']['name']} — {m['source'].get('author', 'unknown author')} — {m['source'].get('url', '')}",
        'license': m['source']['license'],
        'licenseUrl': m['source'].get('licenseUrl'),
        'instrument': m['source'].get('instrument'),
        'recording': m['source'].get('recording'),
        'originalFiles': m['source'].get('files'),
        'format': f"{m['format']}, {m['sampleRate']} Hz, {m['channels']} channel",
        'velocityLayers': layers,
        'rootNotes': roots,
        'rootSpacingSemitones': max((b - a for a, b in zip(roots, roots[1:])), default=0),
        'fileCount': len(files),
        'bytes': entry['bytes'],
        'files': [f"public/samples/{m['id']}/{f}" for f in files],
        'fileDetails': [{'file': f['file'], 'root': f['root'], 'layer': f['layer'], 'seconds': f['seconds'], 'sourceFile': f.get('sourceFile')} for f in m['files']],
        'processing': m.get('processing'),
        'notes': m.get('notes', []),
        'attribution': 'public/samples/LICENSES.md',
    })

details = {
    '$schema': 'https://stagebench.local/schemas/implementation-details.schema.json',
    'version': 1,
    'phase': 2,
    'variant': 'stage-4-73',
    'audio': {
        'strategy': (
            'One AudioContext. Piano notes are AudioBufferSourceNodes playing either recorded, bundled Ogg Vorbis one-shots '
            '(Grand, Upright, Electric, Clav, Digital, Misc models — decoded at runtime with @wasm-audio-decoders/ogg-vorbis) or '
            'generated buffers (the Additive Piano model and the fallback voice, rendered by src/audio/pianoRenderer.ts). '
            'Each voice feeds a per-voice GainNode → per-layer bus GainNode → LayerChain AudioWorkletNode (Timbre EQ, String Res, '
            'Mod 1, Mod 2, Delay, Amp Sim/EQ, Compressor, Reverb — pure TypeScript DSP in src/dsp/) → layer level GainNode → '
            'optionally the shared Rotary AudioWorkletNode (To Rotary) → master GainNode (Master Level) → master limiter '
            'AudioWorkletNode → destination. If AudioWorklet is unavailable the same DSP classes run in a ScriptProcessorNode. '
            'Recorded samples, generated buffers and the live fallback oscillator are always labelled as what they are.'
        ),
        'graph': [
            'voice: AudioBufferSourceNode (+2 detuned copies through StereoPannerNode + GainNode for Unison) → voice GainNode',
            'layer: bus GainNode → LayerChain processor (timbre → stringRes → mod1 → mod2 → delay → ampEq → compressor → reverb) → level GainNode',
            'routing: level → master GainNode, or level → shared Rotary processor → master GainNode when the layer\'s Amp Sim/EQ model is To Rotary',
            'master: master GainNode (Master Level knob, 15 ms ramps) → MasterUnit processor (limiter, threshold 0.95) → AudioContext.destination',
        ],
        'sampleSources': sample_sources,
        'generatedSources': [
            {
                'name': 'Additive Piano (Digital model "digital-additive") and the labelled fallback voice',
                'kind': 'generated-buffer',
                'generator': 'src/audio/pianoRenderer.ts (renderPianoNote)',
                'description': (
                    'Up to 28 inharmonic partials with a hammer-position comb filter, velocity-dependent brightness, two-stage exponential '
                    'decay, a 2 ms attack ramp and a 9 ms seeded-noise thump, rendered lazily per note and velocity layer into Float32 '
                    'AudioBuffers (LRU cache of 64). Generated by code at runtime; it is not a recording. It is selectable as the second '
                    'Digital model and is the playable fallback whenever a recorded set fails to load (status: fallback, "Piano not found").'
                ),
                'velocityLayers': 3,
                'layerRepresentativeVelocities': [32, 72, 112],
                'license': 'Original code written for this candidate; no third-party audio material.',
            },
            {
                'name': 'Fallback triangle tone',
                'kind': 'live-synthesis',
                'generator': 'src/audio/engine.ts (fallbackVoice, OscillatorNode)',
                'description': 'Only used when the generated renderer itself throws: a triangle OscillatorNode with a 5 ms attack and 2.5 s exponential decay through the same voice, layer and master path. Labelled "fallback oscillator" in the status strip and Program display.',
                'license': 'Original code written for this candidate.',
            },
            {
                'name': 'Effect processing (Mod 1, Mod 2, Delay, Amp Sim/EQ, Compressor, Reverb, Rotary, Timbre, String Res, master limiter)',
                'kind': 'live-synthesis',
                'generator': 'src/dsp/*.ts hosted by src/dsp/worklet.ts (AudioWorklet) or src/audio/browserProcessor.ts (ScriptProcessor fallback)',
                'description': (
                    'Algorithmic DSP written for this candidate: LFO / envelope modulators, modulated delay lines, all-pass phasers, a feedback delay with '
                    'in-loop filters, RBJ biquad EQ with documented amp / cabinet approximations (Twin, JC, Small) and 24 dB resonant filters, a '
                    'feed-forward compressor, comb/all-pass reverbs (Room, Booth, Stage, Hall, Cathedral) plus a dispersive spring model, a horn + '
                    'bass-rotor rotary with smooth acceleration, sympathetic-string comb resonators and a peak limiter. No impulse responses or '
                    'recordings are used; the same classes render offline in the tests.'
                ),
                'license': 'Original code written for this candidate.',
            },
        ],
        'decoder': {
            'name': '@wasm-audio-decoders/ogg-vorbis 0.1.20',
            'license': 'MIT (libvorbis BSD-3-Clause)',
            'use': 'Decodes the bundled Ogg Vorbis samples in the browser (Web Worker) and in the Node test-suite; decoding is serialised on one instance.',
        },
        'notes': [
            'Web Audio is created lazily on the first key press or the Start audio button; the sample library starts loading on page load (no audio context needed) and the status strip / Program display report loading progress, ready, error (no AudioContext), and fallback (a set failed to load: the generated Additive Piano plays, labelled fallback, and the type LED flashes).',
            'Sustain (UI pedal button, Shift key, MIDI CC64) is honoured only while SUSTPED is on (Shift + Layer A toggles it). PSTICK (Shift + Layer B) lets the pitch stick bend the Piano section ±2 semitones.',
            'Polyphony is capped at 32 voices across both layers; the oldest sounding voice is stolen deterministically with a 20 ms release. Release is a 300 ms exponential ramp (550 ms with Soft Release; unchanged for Clav-type models), retriggered notes release in 30 ms, all-notes-off in 80 ms.',
            'Tests never touch real audio output, MIDI devices or the network: the audio context, DSP host, asset fetching, MIDI access and timers are injected (src/audio/boundaries.ts) and faked in tests (src/audio/fakeAudio.ts); rendered-audio relationships are proved on the real bundled files decoded from disk and on the real src/dsp classes (src/audio/offlinePiano.ts, src/dsp/offline.ts).',
            'Group mode copies the focused Piano layer\'s chain to both layers; Global mode (Delay, Compressor, Reverb) shares one setting and on-state across every chain; the Organ and Synth chains are stored so their focus edits go somewhere honest, but they process no audio until Phase 3.',
        ],
    },
    'controls': {
        'functional': [
            'piano.on, piano.layer-a.on, piano.layer-b.on (Shift: SUSTPED / PSTICK), piano.layer-a.level, piano.layer-b.level, piano.octave-down/up, piano.type, piano.model, piano.timbre, piano.acoustics (Soft Release / String Res), piano.kb-touch, piano.unison, piano.dyn-comp',
            'effects.on, effects.focus.organ/piano/synth (Shift + piano: Group), effects.shift, effects.mod1.*, effects.mod2.*, effects.delay.tempo/feedback/dry-wet/filter (Shift: Ping Pong)/tap/on (Shift: Global), effects.amp.* (model incl. To Rotary, LP24, HP24), effects.comp.amount (Shift: Fast)/on (Shift: Global), effects.reverb.type/tone/dry-wet/on (Shift: Global)',
            'performance.master-level, performance.rotary.speed, performance.rotary.drive, performance.pitch-stick (only when PSTICK is on), program.shift (same Shift latch as effects.shift)',
        ],
        'decorative': 'Every Organ, Synth and Program control (except program.shift), performance.mod-wheel, performance.rotary.organ, performance.rotary.stop-mode, effects.delay.effect: they move or press and change presentation state only.',
        'shiftLatch': 'Pressing SHIFT (effects or program) arms a latch for the next panel press (8 s), so Shift functions are reachable with a single pointer or from the keyboard; holding SHIFT while pressing another button also works with touch.',
    },
    'unsupported': [
        'Soft pedal (una corda) and sostenuto: not claimed, not simulated (piano spec optional; the only pedal is sustain).',
        'Pedal noise and half-pedalling (piano spec excluded): the PED NOISE LED stays off.',
        'Nord Triple Pedal modelling and pedal-type configuration (excluded).',
        'Piano size classes (Sml/Med/Lrg/XL), the INFO view (Shift + Piano Select) and the LIST view, Nord Sound Manager downloads (excluded).',
        'Piano preset library, programs, Live Mode, splits, KB zones (Shift + Octave), scenes, morphs, master clock sync (MST CLK LEDs stay off) — Phase 3 or cut benchmark-wide.',
        'Per-type effect Variations and Reverb Chorale (Shift + selector does not cycle the selector; nothing else happens).',
        'Delay feedback-loop effects (Chor/Vibe/Ens/Flam/Space selector is decorative) and Analog mode (Shift + Tap).',
        'Mod 1 Pump / Wah pedal modes; rotary close mic, stop mode and stop angle; the Organ rotary routing button (the organ is silent until Phase 3).',
        'Global reverb placement after the rotary (excluded): reverb always precedes the rotary.',
        'Organ and Synth effect chains process no audio until Phase 3 (their focus and edits are stored, inaudible and labelled).',
        'Aftertouch, arpeggiator, Extern / Aux KB / MIDI menus (cut benchmark-wide).',
    ],
    'inputs': {
        'pointer': 'pointerdown/up/cancel with per-pointer tracking, glissando across keys, independent multi-touch, velocity from the strike position on the key',
        'computerKeyboard': "physical key codes A W S E D F T G Y H U J K O L P ; ' = C4..F5 (base shifts with Z/X, clamped to the keybed), Shift = sustain, auto-repeat suppressed, blur/visibility-hidden releases everything",
        'midi': 'Web MIDI note on/off with velocity on any channel, CC64 sustain, CC120/123 all notes off; unsupported / requesting / ready / denied / error / disconnected states, disconnect releases the device\'s notes',
    },
    'evidence': {
        'captureHarness': 'scripts/capture.mjs (playwright-core driving the locally installed Chrome; the parent capture harness was not available in this workspace)',
        'directory': 'evidence/',
        'files': ['evidence/stage2-desktop.png', 'evidence/stage2-narrow.png', 'evidence/stage2-capture.json', 'evidence/stage2-visual-audit.md', 'evidence/stage1-desktop.png', 'evidence/stage1-narrow.png', 'evidence/stage1-capture.json', 'evidence/stage1-visual-audit.md'],
    },
    'samplePipeline': {
        'scripts': ['scripts/samples/fetch.sh', 'scripts/samples/build.py', 'scripts/samples/validate.py', 'scripts/samples/README.md'],
        'librarySizeBytes': sum(e['bytes'] for e in index['sets']),
        'attribution': 'public/samples/LICENSES.md',
    },
}

# every recorded model in the registry must have a bundled set
for set_id in re.findall(r"setId: '([a-z0-9-]+)'", registry):
    assert any(s['setId'] == set_id for s in sample_sources), f'registry set {set_id} has no bundled manifest'

with open(os.path.join(ROOT, 'IMPLEMENTATION_DETAILS.json'), 'w') as f:
    json.dump(details, f, indent=2, ensure_ascii=False)
    f.write('\n')
print('wrote IMPLEMENTATION_DETAILS.json with', len(sample_sources), 'sample sets')
